### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Rovanion** [tatut/reagent-leaflet#1]
Hi,
I recently started playing around with Leaflet in cljs and found your library which hopefully solves some of the mutate happy parts of its API. Now my question is this: Are you willing to license your code to the world in any shape or form, perhaps under the EPL as is common in the Clojure world?

**Comment by tatut** [comment]
Sure, but this repo is pretty basic. 

I think you would be better off using react-leaflet which is packaged in cljsjs.

**Comment by Rovanion** [comment]
That looks interesting.

But I've already gotten started working on reagent-leaflet bringing its dependencies up to date and splitting out the example into its own project. We'll see where I end up.

**Comment by tatut** [comment]
License added, MIT.
